package dao;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

public class AddressRepository {

	private String url = "jdbc:hsqldb:hsql://localhost/workdb";
	private Connection connection;
	private String createTableSql = 
			"CREATE TABLE address("
			+ "id bigint GENERATED BY DEFAULT AS IDENTITY,"
			+ "streetName VARCHAR(50),"
			+ "streetNumber bigint,"
			+ "houseNumber VARCHAR(10),"
			+ "city VARCHAR(50),"
			+ "postcode VARCHAR(5)"			
			+ ")";
	
	Statement createTable;
	
	
	public AddressRepository(){
		
		try {
			
			connection = DriverManager.getConnection(url);
			createTable = connection.createStatement();
			ResultSet rs = connection.getMetaData().getTables(null, null, null, null);
			boolean tableExists = false;
			while(rs.next()){
				if("address".equalsIgnoreCase(rs.getString("TABLE_NAME"))){
					tableExists=true;
					break;
				}
			}
			if(!tableExists)
				createTable.executeUpdate(createTableSql);
			
		} catch (SQLException e) {
			e.printStackTrace();
		}
	}
	
}
