package dao;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

public class AddressRepository {
	private String url = "jdbc:hsqldb:hsql://localhost/workdb";
	private Connection connection;
	private Statement createTable;
	
	private String createTableSql = (
        "CREATE TABLE Address(" +
            "id BIGINT GENERATED BY DEFAULT AS IDENTITY," +
            "city VARCHAR(200)," +
            "street VARCHAR(255)," +
            "house_number INT" +
        ")"
    );
	
	public AddressRepository() {
		try {
			connection = DriverManager.getConnection(url);
			createTable = connection.createStatement();

			boolean tableExists = false;
			ResultSet rs = connection.getMetaData().getTables(null, null, null, null);
			while(rs.next()){
				if("Address".equalsIgnoreCase(rs.getString("TABLE_NAME"))){
					tableExists=true;
					break;
				}
			}
			
			if(!tableExists)
				createTable.executeUpdate(createTableSql);
		} catch (SQLException e) {
			e.printStackTrace();
		}
	}
}
