package dao;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

public class AdresRepository {

	private String url = "jdbc:hsqldb:hsql://localhost/workdb";
	private Connection connection;
	private String createTableSql = 
			"CREATE TABLE person("
			+ "kodpoczt bigint GENERATED BY DEFAULT AS IDENTITY,"
			+ "miasto VARCHAR(30),"
			+ "ulica VARCHAR(50),"
			+ "kraj VARCHAR(50),"			
			+ "nrdomu int"
			+ "nrmieszk int"
			+ ")";
	
	Statement createTable;
	
	
	public AdresRepository(){
		
		try {
			
			connection = DriverManager.getConnection(url);
			createTable = connection.createStatement();
			createTable.executeUpdate(createTableSql);
			
		} catch (SQLException e) {
			e.printStackTrace();
		}
	}
	
	
}
