package dao;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

public class filmlist {

	private String url = "jdbc:hsqldb:hsql://localhost/workdb";
	private Connection connection;
	private Statement createTable;	
	
	private String createTableSql = "CREATE TABLE Film("
			+ "id BIGINT GENERATED BY DEFAULT AS IDENTITY,"
			+ "name VARCHAR(20),"
			+ "director VARCHAR(100),"
			+ "genre VARCHAR(40)"
			+ "year INT"
			+ ")";

	public filmlist(){
		
		try {
			connection = DriverManager.getConnection(url);
			createTable = connection.createStatement();
			createTable.executeUpdate(createTableSql);
			
			
		} catch (SQLException e) {
			e.printStackTrace();
		}
		
	}
		
	
}
