package dao;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import domain.Person;

public class PersonRepository {

	private String url = "jdbc:hsqldb:hsql://localhost/workdb";
	private Connection connection;
	private Statement createTable;
	private PreparedStatement insert;
	
	private String createTableSql = "CREATE TABLE Person("
			+ "id BIGINT GENERATED BY DEFAULT AS IDENTITY,"
			+ "name VARCHAR(20),"
			+ "surname VARCHAR(50),"
			+ "age INT"
			+ ")";

	private String insertSql ="INSERT INTO Person (name, surname, age) VALUES(?,?,?)";
	
	
	
	
	public PersonRepository(){
		
		try {
			connection = DriverManager.getConnection(url);
			createTable = connection.createStatement();
			insert = connection.prepareStatement(insertSql);
			
			boolean tableExists = false;
			ResultSet rs = connection.getMetaData().getTables(null, null, null, null);
			while(rs.next()){
				if("Person".equalsIgnoreCase(rs.getString("TABLE_NAME"))){
					tableExists=true;
					break;
				}
			}
			
			if(!tableExists)
				createTable.executeUpdate(createTableSql);
			
		} catch (SQLException e) {
			e.printStackTrace();
		}
		
	}
	
	public void add(Person person){
		try{
		insert.setString(1, person.getName());
		insert.setString(2, person.getSurname());
		insert.setInt(3, person.getAge());
		insert.executeUpdate();
		}catch(SQLException ex){
			ex.printStackTrace();
		}
	}
	
}
